name: OLS_GLM
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _r-mutex=1.0.1
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.6.15
  - cairo=1.18.4
  - cctools_osx-arm64=1010.6
  - clang=20.1.6
  - clang-20=20.1.6
  - clang_impl_osx-arm64=20.1.6
  - clang_osx-arm64=20.1.6
  - clangxx=20.1.6
  - clangxx_impl_osx-arm64=20.1.6
  - clangxx_osx-arm64=20.1.6
  - compiler-rt=20.1.6
  - compiler-rt_osx-arm64=20.1.6
  - curl=8.14.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gfortran_impl_osx-arm64=13.3.0
  - gfortran_osx-arm64=13.3.0
  - gmp=6.3.0
  - graphite2=1.3.13
  - gsl=2.7
  - harfbuzz=11.2.1
  - icu=75.1
  - isl=0.26
  - krb5=1.21.3
  - ld64_osx-arm64=951.9
  - lerc=4.0.0
  - libasprintf=0.24.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.6
  - libcurl=8.14.0
  - libcxx=20.1.6
  - libcxx-devel=20.1.6
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgettextpo=0.24.1
  - libgfortran=5.0.0
  - libgfortran-devel_osx-arm64=13.3.0
  - libgfortran5=14.2.0
  - libglib=2.84.2
  - libiconv=1.18
  - libintl=0.24.1
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm20=20.1.6
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libnghttp2=1.64.0
  - libopenblas=0.3.29
  - libpng=1.6.47
  - libsqlite=3.50.0
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libuv=1.51.0
  - libwebp-base=1.5.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=20.1.6
  - llvm-tools=20.1.6
  - llvm-tools-20=20.1.6
  - make=4.4.1
  - mpc=1.3.1
  - mpfr=4.2.1
  - ncurses=6.5
  - nlopt=2.9.0
  - numpy=2.2.6
  - openssl=3.5.0
  - pandoc=3.7.0.2
  - pango=1.56.3
  - pcre2=10.45
  - pip=25.1.1
  - pixman=0.46.0
  - python=3.13.3
  - python_abi=3.13
  - r-abind=1.4_5
  - r-askpass=1.2.1
  - r-assertthat=0.2.1
  - r-backports=1.5.0
  - r-base=4.4.3
  - r-base64enc=0.1_3
  - r-bayestestr=0.16.0
  - r-bit=4.6.0
  - r-bit64=4.6.0_1
  - r-blob=1.2.4
  - r-boot=1.3_31
  - r-broom=1.0.8
  - r-bslib=0.9.0
  - r-cachem=1.1.0
  - r-callr=3.7.6
  - r-car=3.1_3
  - r-cardata=3.0_5
  - r-caret=6.0_94
  - r-cellranger=1.1.0
  - r-class=7.3_23
  - r-cli=3.6.5
  - r-clipr=0.8.0
  - r-clock=0.7.3
  - r-codetools=0.2_20
  - r-colorspace=2.1_1
  - r-colourpicker=1.3.0
  - r-commonmark=1.9.5
  - r-conflicted=1.2.0
  - r-conquer=1.3.3
  - r-correlation=0.8.7
  - r-corrplot=0.95
  - r-cowplot=1.1.3
  - r-cpp11=0.5.2
  - r-crayon=1.5.3
  - r-curl=6.2.2
  - r-data.table=1.17.4
  - r-datawizard=1.1.0
  - r-dbi=1.2.3
  - r-dbplyr=2.5.0
  - r-deriv=4.1.6
  - r-diagram=1.6.5
  - r-digest=0.6.37
  - r-doby=4.6.27
  - r-dplyr=1.1.4
  - r-dtplyr=1.3.1
  - r-e1071=1.7_16
  - r-effectsize=1.0.1
  - r-ellipsis=0.3.2
  - r-emmeans=1.11.1
  - r-estimability=1.5.1
  - r-evaluate=1.0.3
  - r-fansi=1.0.6
  - r-farver=2.1.2
  - r-fastmap=1.2.0
  - r-fontawesome=0.5.3
  - r-forcats=1.0.0
  - r-foreach=1.5.2
  - r-formula=1.2_5
  - r-fs=1.6.6
  - r-future=1.49.0
  - r-future.apply=1.11.3
  - r-gargle=1.5.2
  - r-gbrd=0.4.12
  - r-generics=0.1.4
  - r-ggcorrplot=0.1.4.1
  - r-ggextra=0.10.1
  - r-ggfortify=0.4.17
  - r-ggplot2=3.5.2
  - r-globals=0.18.0
  - r-glue=1.8.0
  - r-googledrive=2.1.1
  - r-googlesheets4=1.1.1
  - r-gower=1.0.1
  - r-gparotation=2025.3_1
  - r-gridextra=2.3
  - r-gtable=0.3.6
  - r-hardhat=1.4.1
  - r-haven=2.5.4
  - r-highr=0.11
  - r-hms=1.1.3
  - r-htmltools=0.5.8.1
  - r-htmlwidgets=1.6.4
  - r-httpuv=1.6.15
  - r-httr=1.4.7
  - r-ids=1.0.1
  - r-insight=1.3.0
  - r-ipred=0.9_15
  - r-isoband=0.2.7
  - r-iterators=1.0.14
  - r-jquerylib=0.1.4
  - r-jsonlite=2.0.0
  - r-kableextra=1.4.0
  - r-kernsmooth=2.23_26
  - r-knitr=1.50
  - r-labeling=0.4.3
  - r-later=1.4.2
  - r-lattice=0.22_7
  - r-lava=1.8.1
  - r-lifecycle=1.0.4
  - r-listenv=0.9.1
  - r-lme4=1.1_37
  - r-lubridate=1.9.4
  - r-magrittr=2.0.3
  - r-mass=7.3_64
  - r-matrix=1.7_3
  - r-matrixmodels=0.5_4
  - r-matrixstats=1.5.0
  - r-memoise=2.0.1
  - r-mgcv=1.9_3
  - r-microbenchmark=1.5.0
  - r-mime=0.13
  - r-miniui=0.1.2
  - r-minqa=1.2.8
  - r-mnormt=2.1.1
  - r-modelbased=0.11.2
  - r-modelmetrics=1.2.2.2
  - r-modelr=0.1.11
  - r-munsell=0.5.1
  - r-mvtnorm=1.3_3
  - r-nlme=3.1_168
  - r-nloptr=2.2.1
  - r-nnet=7.3_20
  - r-numderiv=2016.8_1.1
  - r-openssl=2.3.3
  - r-parallelly=1.45.0
  - r-parameters=0.26.0
  - r-patchwork=1.3.0
  - r-pbkrtest=0.5.4
  - r-performance=0.14.0
  - r-pillar=1.10.2
  - r-pkgconfig=2.0.3
  - r-plyr=1.8.9
  - r-prettyunits=1.2.0
  - r-proc=1.18.5
  - r-processx=3.8.6
  - r-prodlim=2025.04.28
  - r-progress=1.2.3
  - r-progressr=0.15.1
  - r-promises=1.3.2
  - r-proxy=0.4_27
  - r-ps=1.9.1
  - r-psych=2.5.3
  - r-purrr=1.0.4
  - r-quantreg=6.1
  - r-r6=2.6.1
  - r-ragg=1.4.0
  - r-rappdirs=0.3.3
  - r-rbibutils=2.3
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.0.14
  - r-rcpparmadillo=14.4.2_1
  - r-rcppeigen=0.3.4.0.2
  - r-rdpack=2.6.4
  - r-readr=2.1.5
  - r-readxl=1.4.5
  - r-recipes=1.3.1
  - r-reformulas=0.4.1
  - r-rematch=2.0.0
  - r-rematch2=2.1.2
  - r-reprex=2.1.1
  - r-reshape2=1.4.4
  - r-rlang=1.1.6
  - r-rmarkdown=2.29
  - r-rpart=4.1.24
  - r-rstudioapi=0.17.1
  - r-rvest=1.0.4
  - r-sass=0.4.10
  - r-scales=1.4.0
  - r-see=0.11.0
  - r-selectr=0.4_2
  - r-shape=1.4.6.1
  - r-shiny=1.11.0
  - r-shinyjs=2.1.0
  - r-sourcetools=0.1.7_1
  - r-sparsem=1.84_2
  - r-sparsevctrs=0.3.4
  - r-squarem=2021.1
  - r-stringi=1.8.7
  - r-stringr=1.5.1
  - r-survival=3.8_3
  - r-svglite=2.1.3
  - r-sys=3.4.3
  - r-systemfonts=1.2.3
  - r-textshaping=1.0.1
  - r-tibble=3.2.1
  - r-tidyr=1.3.1
  - r-tidyselect=1.2.1
  - r-tidyverse=2.0.0
  - r-timechange=0.3.0
  - r-timedate=4041.110
  - r-tinytex=0.57
  - r-tmvnsim=1.0_2
  - r-tzdb=0.5.0
  - r-utf8=1.2.5
  - r-uuid=1.2_1
  - r-vctrs=0.6.5
  - r-viridislite=0.4.2
  - r-vroom=1.6.5
  - r-webshot=0.5.5
  - r-withr=3.0.2
  - r-xfun=0.52
  - r-xml2=1.3.8
  - r-xtable=1.8_4
  - r-yaml=2.3.10
  - readline=8.2
  - sigtool=0.1.3
  - tapi=1300.6.5
  - tk=8.6.13
  - tktable=2.10
  - tzdata=2025b
  - zlib=1.3.1
  - zstd=1.5.7
